Add environment variable validation in GitHub Actions workflow
- Implemented checks to ensure all required environment variables are set before executing further commands, enhancing error handling and preventing runtime failures.

diff --git a/.github/workflows/neon_workflow.yml b/.github/workflows/neon_workflow.yml
--- a/.github/workflows/neon_workflow.yml
+++ b/.github/workflows/neon_workflow.yml
@@ -146,6 +146,13 @@ jobs:
           DB_URL_UNPOOLED: ${{ steps.create_neon_branch.outputs.db_url }}
           INFORMATIONAL_NEON_BRANCH_NAME: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
         run: |
+
+          # fail if any of above environment variables are not set
+          if [ -z "$RAILWAY_API_TOKEN" ] || [ -z "$RAILWAY_PROJECT_ID" ] || [ -z "$RAILWAY_ENV_ID" ] || [ -z "$RAILWAY_FASTAPI_SERVICE_ID" ] || [ -z "$DB_URL_POOLED" ] || [ -z "$DB_URL_UNPOOLED" ] || [ -z "$INFORMATIONAL_NEON_BRANCH_NAME" ]; then
+            echo "Error: One or more environment variables are not set"
+            exit 1
+          fi
+
           # Update DATABASE_URL (pooled connection) 
           curl -s --request POST \
             --url https://backboard.railway.com/graphql/v2 \
